version: 2.1

orbs:
  node: circleci/node@4.7
  cypress: cypress-io/cypress@3

workflows:
  sample:
    jobs:
      - cypress/run:
          install-command: npm install
          start-command: npm start & wait-on http://localhost:8080
          cypress-command: npm run test:e2e