version: 2.1

orbs:
  node: circleci/node@4.7
  cypress: cypress-io/cypress@3

workflows:
  sample:
    jobs:
      - cypress/run:
          install-command: npm install && echo hello
          start-command: npm run test:e2e